server:
  port: 8080


token:
  expiration_time: 864000000
  secret: 'token_secret'


spring:
  application:
    name: user-service
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
##   driver-class-name: org.mariadb.jdbc.Driver
#     url: jdbc:mariadb://127.0.0.1:3306/mydb
#    username: root
#    password: 1234
#  zipkin:
#    base-url: http://localhost:9411
#    enable: true
#  sleuth:
#    sampler:
#      probability: 1.0

  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/chat?
    hikari:
      username: root
      password: mariadb

# 유레카 클라이언트
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#     유저서버 등록, 랜덤포트
#    eureka-server-url:
#      defaultZone: http://localhost:8761/eureka
  service-url:
    defaultZone: http://192.168.201.108:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    ip-address: 192.168.201.108
    hostname: 192.168.201.108

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info
